sonar.projectKey=hugo-brb_ChaosPizzaAPI
sonar.organization=hugo-brb

# Optional properties
sonar.projectName=chaos-pizza-api
sonar.projectVersion=1.0.0
sonar.sources=.
sonar.exclusions=__tests__/**, coverage/**, node_modules/**

# Tests configuration
sonar.tests=__tests__
# Coverage report location
sonar.javascript.lcov.reportPaths=coverage/lcov.info

sonar.sourceEncoding=UTF-8
